# Site Info
title:              "Philip Mohun"
description:        "Personal Blog"
author_name:        "Philip Mohun" 
logo_url:           './assets/selfphoto.jpg' # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://pmohun.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

